DROP TABLE IF EXISTS libros;

CREATE TABLE libros(
  id INT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(100) NOT NULL UNIQUE,
  autor VARCHAR(50) DEFAULT NULL,
  precio DOUBLE DEFAULT 0,
  PRIMARY KEY(id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
